from enum import Enum


class OPTION(Enum):
    LIST_ONLINE_USERS = '1'
    LIST_CURRENT_GROUPS = '2'
    SEND_MESSAGE_TO_USER = '3'
    CREATE_GROUP = '4'
    JOIN_GROUP = '5'
    SEND_MESSAGE_TO_GROUP = '6'
    BROADCAST_MESSAGE = '7'
    CLOSE_CONNECTION = '8'

